language: bash

services:
  - docker

#
# https://docs.travis-ci.com/user/environment-variables/
#
env:
  # All the env variables need put into a single line.
  - IMAGE_NAME=jccdevbox/docker-android-build-box SOURCE_BRANCH=$TRAVIS_BRANCH SOURCE_COMMIT=$TRAVIS_COMMIT DOCKER_TAG=latest

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./hooks/pre_build

  # Wait 50 minutes to avoid travis timeout.
  # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
  - travis_wait 50 ./hooks/build

script:
  # - curl 127.0.0.1:8000
  - docker run -it --rm $IMAGE_NAME flutter --version
  - docker tag jccdevbox/docker-android-build-box:latest jccdevbox/docker-android-build-box:${TRAVIS_COMMIT}
  - docker push jccdevbox/docker-android-build-box:${TRAVIS_COMMIT}

after_script:
  - ./hooks/post_build
  - docker rmi $IMAGE_NAME

